project:
  type: website
  output-dir: docs
  resources:
  - lecture.ipynb

format:
  revealjs:
    theme: black
    slide-number: true
    cold-fold: false
    incrememental: true
  
execute:
  freeze: auto