project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: black
    slide-number: true
    cold-fold: false
    incrememental: true
  
execute:
  freeze: auto

# Enable the Pyodide filter for client-side Python execution (real-time)
filters:
  - pyodide