project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  resources:
  - lecture.ipynb

format:
  revealjs:
    theme: dracula #dracula or night or simple
    slide-number: true
    cold-fold: false
    incrememental: true
  
execute:
  freeze: auto